# ------------------------------------------------------------------------------
# List of folders containing backup configurations.
#
# Example:
#  - backup-configs-enabled
#------------------------------------------------------------------------------
backup_configs_folders:
   - backup-configs-enabled
